### ISSUE TITLE
Information about indicator

### ISSUE THREAD

**Issue by alancastro** [9nix6/Median-and-Turbo-Renko-indicator-bundle#1]
Is VWAP indicator available for Renko?

**Comment by 9nix6** [comment]
Hi, Not yet. The indicator will soon be updated to version 1.46 and I will release VWAP for Renko charts shortly afterwards.

**Comment by alancastro** [comment]
Great! I just bought your indicator.
Do you have plans to implement others indicators into it? Like MACD?

**Comment by 9nix6** [comment]
Yes. As soon as version 1.46 goes live I will release MACD. I have it coded already. It will be a separate indicator that you attach directly to the Renko chart.

**Comment by alancastro** [comment]
Hi, I've seen version 1.46 was released. 
Can you post here in this repository an example how to use the API to import indicators?

Cheers!

**Comment by 9nix6** [comment]
Done. Sorry for the delay. I'll also be posting a helper class for patching existing MQL5 indicators so they can be attached directly to the Renko chart.
