### ISSUE TITLE
EMA indicator

### ISSUE THREAD

**Issue by vmlellis** [9nix6/Median-and-Turbo-Renko-indicator-bundle#3]
Could you develop an exponential moving average indicator (EMA)?
It's possible only add 2 averages with the main indicator.

**Comment by 9nix6** [comment]
Hi, You can use MedianRenko_gmma.mq5 for this. It has 12 MAs.
If that does not work for you, let me know. I'll consider adding an MA to the repository.

**Comment by 9nix6** [comment]
The latest version has 3 MAs built is and I also added the MedianRenko_MA to the repository so you can add more MAs (EMA included).
