### ISSUE TITLE
missing file EA_Logic.mqh

### ISSUE THREAD

**Issue by marceloscunha** [9nix6/Median-and-Turbo-Renko-indicator-bundle#5]
missing file EA_Logic.mqh

**Comment by 9nix6** [comment]
Thanks. Please change the line from
`#include "EA_Login.mqh`
to
`#include "Renko_EA_Logic.mqh"`
The problem should be fixed now as well since I edited the file on GitHub.

**Comment by 9nix6** [comment]
`#include "Renko_EA_Logic.mqh"`
