### ISSUE TITLE
'_SuperTrend' - undeclared identifier	Renko_EA_Logic.mqh	696

### ISSUE THREAD

**Issue by marceloscunha** [9nix6/Median-and-Turbo-Renko-indicator-bundle#6]
'_SuperTrend' - undeclared identifier	Renko_EA_Logic.mqh	696

if((ShowChannel == _SuperTrend) && (this.inputs.SuperTrendFilter != FILTER_MODE_OFF))

**Comment by 9nix6** [comment]
Thanks. I downloaded the full code to a clean install of MT5 fixed and tested the compilation so all should be good now.
