### ISSUE TITLE
Problems with renko Bundle on MT5 Build 3320

### ISSUE THREAD

**Issue by tzahimaimon** [9nix6/Median-and-Turbo-Renko-indicator-bundle#8]
A lot of errors regarding the indicators when I put them on Renko chart: 
![image](https://user-images.githubusercontent.com/19863282/178774458-0ca6327e-0191-4b8e-b15d-e86267bdb3ec.png)

each time the indicators disappearing and sometimes after building new renko candle thier coming back in other times like now the indicator report that they cannot access the Renko Main indicator:

![image](https://user-images.githubusercontent.com/19863282/178774984-90493615-85ad-4d36-b105-e61bbf2b6848.png)

**Comment by tzahimaimon** [comment]
I've tried multiple restarts of the computer and the MT Platform and the problems presists

**Comment by 9nix6** [comment]
Which version of P-Renko Ultimate are you using and which indicators have you attached?

**Comment by tzahimaimon** [comment]
The version of P-Renko is 3.19 and I've tried to put OBV, WeisWave and Oscillator Candle.. BUT I think I found the problem... the system us working fine now.
let me check again and if there will be more issues I open new one 
Thank you !
