### ISSUE TITLE
Using Both Renko and Range on the same Terminal

### ISSUE THREAD

**Issue by tzahimaimon** [9nix6/Median-and-Turbo-Renko-indicator-bundle#9]
I Have both Median Renko and Range indicators how can I Use them both on the same MT Terminal in diffrent Charts ?

**Comment by 9nix6** [comment]
You should be able to use both of them without any problems. Please keep in mind that you need to open 2 different charts and if they are for the same instrument (i.e. EURUSD), you need to use different timeframes. 

For example, put renko on EURUSD,M30, and range bars on EURUSD,H1.

**Comment by tzahimaimon** [comment]
The Issue is when i'm building my own indicator and want to Compile this indicator for Range or  Renko or for Both because there is a #define in CustomBarConfig.mqh that refers to the correct indicator on the chart. 
And if I compile with the incorrect statement it's not working fine. But the define is in the CustomBarConfig.mqh and its already deinfed there.

**Comment by 9nix6** [comment]
You need to create 2 separate folders (for example. "Renko Indicators" and "RangeBar indicators" and have 2 compilations for the individual charts. This is how we distribute the indicators with the individual charting systems.
